name: Manual Dev build

on:
  workflow_dispatch:

jobs:
  build:
    name: Test Android ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build dev
        run: ./gradlew assembleDevRelease
